// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using parking_app.Data;

#nullable disable

namespace parking_app.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413145217_ConnectionsAdded")]
    partial class ConnectionsAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("parking_app.Models.ParkingPlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PricePerHour")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ParkingPlaces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 50,
                            Name = "Centrum - Hlavní",
                            PricePerHour = 40
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 200,
                            Name = "OC Nová Karolina",
                            PricePerHour = 0
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 500,
                            Name = "Letiště Václava Havla",
                            PricePerHour = 80
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 30,
                            Name = "Nádraží Svinov",
                            PricePerHour = 20
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 45,
                            Name = "Podzemní garáže Divadlo",
                            PricePerHour = 50
                        });
                });

            modelBuilder.Entity("parking_app.Models.Spz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Spz");
                });

            modelBuilder.Entity("parking_app.Models.SpzParkingPlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParkingPlaceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpzId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParkingPlaceId");

                    b.HasIndex("SpzId");

                    b.ToTable("SpzParkingPlaces");
                });

            modelBuilder.Entity("parking_app.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f9fdb71a-0915-4cbd-85b8-6c580bff797f",
                            Email = "admin@parking.cz",
                            EmailConfirmed = true,
                            FName = "Hlavní",
                            LName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@PARKING.CZ",
                            NormalizedUserName = "ADMIN@PARKING.CZ",
                            PasswordHash = "AQAAAAIAAYagAAAAEKVpnlXUPcajsgF8dAyxLWOwV1KDDpDdk5PaFkU0xn+ttXRzX5dvFHWkScEcQqtBTg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "admin_guid",
                            TwoFactorEnabled = false,
                            UserName = "admin@parking.cz"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a3f2e896-d0d6-44b2-b121-0194cbec3974",
                            Email = "pepa@seznam.cz",
                            EmailConfirmed = true,
                            FName = "Pepa",
                            LName = "Novák",
                            LockoutEnabled = false,
                            NormalizedEmail = "PEPA@SEZNAM.CZ",
                            NormalizedUserName = "PEPA@SEZNAM.CZ",
                            PasswordHash = "AQAAAAIAAYagAAAAEOwAgdTvJchd/t8TewzwgR3gZ6eTGXUXgEqH1CmvF+7+dgPG5kRL+wAQjY+XTxSBPA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "user_guid",
                            TwoFactorEnabled = false,
                            UserName = "pepa@seznam.cz"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("parking_app.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("parking_app.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("parking_app.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("parking_app.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("parking_app.Models.ParkingPlace", b =>
                {
                    b.OwnsOne("parking_app.Models.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<int>("ParkingPlaceId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("city");

                            b1.Property<string>("HouseNumber")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("houseNumber");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("postalCode");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("street");

                            b1.HasKey("ParkingPlaceId");

                            b1.ToTable("ParkingPlaces");

                            b1.WithOwner()
                                .HasForeignKey("ParkingPlaceId");

                            b1.HasData(
                                new
                                {
                                    ParkingPlaceId = 1,
                                    City = "Praha",
                                    HouseNumber = "1",
                                    PostalCode = "110 00",
                                    Street = "Václavské náměstí"
                                },
                                new
                                {
                                    ParkingPlaceId = 2,
                                    City = "Ostrava",
                                    HouseNumber = "4",
                                    PostalCode = "702 00",
                                    Street = "Jantarová"
                                },
                                new
                                {
                                    ParkingPlaceId = 3,
                                    City = "Praha",
                                    HouseNumber = "6",
                                    PostalCode = "161 00",
                                    Street = "Aviatická"
                                },
                                new
                                {
                                    ParkingPlaceId = 4,
                                    City = "Ostrava",
                                    HouseNumber = "79",
                                    PostalCode = "721 00",
                                    Street = "Peterkova"
                                },
                                new
                                {
                                    ParkingPlaceId = 5,
                                    City = "Brno",
                                    HouseNumber = "17",
                                    PostalCode = "602 00",
                                    Street = "Rooseveltova"
                                });
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("parking_app.Models.Spz", b =>
                {
                    b.HasOne("parking_app.Models.User", "User")
                        .WithMany("Spzs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("parking_app.Models.SpzParkingPlace", b =>
                {
                    b.HasOne("parking_app.Models.ParkingPlace", "ParkingPlace")
                        .WithMany("SpzParkingPlaces")
                        .HasForeignKey("ParkingPlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("parking_app.Models.Spz", "Spz")
                        .WithMany("SpzParkingPlaces")
                        .HasForeignKey("SpzId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("parking_app.Models.ValueObjects.Date", "Date", b1 =>
                        {
                            b1.Property<int>("SpzParkingPlaceId")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("End")
                                .HasColumnType("TEXT")
                                .HasColumnName("end");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("TEXT")
                                .HasColumnName("start");

                            b1.HasKey("SpzParkingPlaceId");

                            b1.ToTable("SpzParkingPlaces");

                            b1.WithOwner()
                                .HasForeignKey("SpzParkingPlaceId");
                        });

                    b.Navigation("Date")
                        .IsRequired();

                    b.Navigation("ParkingPlace");

                    b.Navigation("Spz");
                });

            modelBuilder.Entity("parking_app.Models.ParkingPlace", b =>
                {
                    b.Navigation("SpzParkingPlaces");
                });

            modelBuilder.Entity("parking_app.Models.Spz", b =>
                {
                    b.Navigation("SpzParkingPlaces");
                });

            modelBuilder.Entity("parking_app.Models.User", b =>
                {
                    b.Navigation("Spzs");
                });
#pragma warning restore 612, 618
        }
    }
}
